In [12]:
import pandas as pd
from chardet.universaldetector import UniversalDetector
import json
from pprint import pprint
import warnings
warnings.filterwarnings('ignore')

"""countries_data = pd.read_csv('data/countries.csv', sep=';') # Загружаем данные из файла в переменную, создавая объект DataFrame
countries_data.to_csv('data/countries.txt', index=False, sep=' ') # Выгружаем данные из DataFrame в CSV-файл и сохраняем файл в папке data
txt_df = pd.read_table('data/countries.txt', sep=' ', index_col=['country'])# Загружаем данные из файла в переменную, создавая объект DataFrame
#display(txt_df) # Выводим содержимое DataFrame на экран
melb_data = pd.read_csv('data/melb_data.csv', header=None) # Загружаем данные из файла в переменную, создавая объект DataFrame
#display(melb_data) # Выводим содержимое DataFrame на экран

data=pd.read_csv('data/ErrorEnCoding.csv', header=None, encoding_errors='replace') # Считываем данные из файла с неизвестной кодировкой в переменную, создавая объект DataFrame
#display(data) # Выводим содержимое DataFrame на экран
 # Импортируем субмодуль chardet.universaldetector
detector = UniversalDetector()
with open('data/ErrorEnCoding.csv', 'rb') as fh:
    for line in fh:
        detector.feed(line)
        if detector.done:
            break
detector.close()

data=pd.read_csv('data/ErrorEnCoding.csv', encoding='koi8-r', header=None )
#display(data)

data = pd.read_table('https://raw.githubusercontent.com/esabunor/MLWorkspace/master/melb_data.csv', sep=',')
#display(data)

data = pd.read_csv('data/students_performance.zip')
#display(data)

compression_opts = dict(method='zip', archive_name='out.csv') # Определяем параметры архивирования — метод сжатия, имя файл в архиве
data.to_csv('data/out.zip', index=False, compression=compression_opts)

grades = pd.read_excel('data/grades.xlsx')
#display(grades.head())

data = pd.read_excel('https://github.com/asaydn/test/raw/master/january.xlsx')
#display(data)

grades = pd.read_excel('data/grades.xlsx', sheet_name='Maths')
#display(grades.head())

grades.to_excel('data/grades_new.xlsx') # Сохраняем данные из DataFrame grades в файл grades_new.xlsx в папке data

sheet1 = pd.read_excel('data/ratings+movies.xlsx', sheet_name='ratings')
sheet2 = pd.read_excel('data/ratings+movies.xlsx', sheet_name='movies')
all=sheet1.merge(sheet2, on='movieId',how='left')
#display(sheet1.info())
#display(sheet2.info())
display(all)

with open('recipes.json') as f: # Открываем файл и связываем его с объектом "f"
    recipes = json.load(f) # Загружаем содержимое открытого файла в переменную recipes
    
#pprint(recipes) # Выводим на экран содержимое переменной recipes, используя функция pprint()
#len(recipes[0]['ingredients'])
#for i in range(len(recipes)): 
#    if recipes[i]['id']==13121: pprint(recipes[i])
    
abc = set()
for i in range(len(recipes)):
    abc.add(recipes[i]['cuisine'])
print(len(abc))

count=dict()
counter=1
for i in range(len(recipes)):
    if recipes[i]['cuisine'] not in count:
        count.update({recipes[i]['cuisine']:counter})
    else:
        count.update({recipes[i]['cuisine']:count.get(recipes[i]['cuisine'])+1})
print(sorted(count.items(), key=lambda x:x[1]))
"""

with open('recipes.json') as f: # Открываем файл и связываем его с объектом "f"
    recipes = json.load(f) # Загружаем содержимое открытого файла в переменную recipes
df = pd.DataFrame(recipes) # Создаём объект DataFrame из списка recipes
display(df) # Выводим на экран первые строки полученного DataFrame
ingredients_list=[]
for i in range(len(df['ingredients'])):
    for j in df['ingredients'][i]:
        if j not in ingredients_list:
            ingredients_list.append(j)
 

for name in ingredients_list:
    df[name] = df['ingredients'].apply(lambda ing: 1 if name in ing else 0)
df['ingredients'] = df['ingredients'].apply(len)

ids=[]
for i in df['id']:
    if i not in ids:
        ids.append(i)

ids

        id      cuisine                                        ingredients
0    10259        greek  [romaine lettuce, black olives, grape tomatoes...
1    25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2    20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3    22213       indian                [water, vegetable oil, wheat, salt]
4    13162       indian  [black pepper, shallots, cornflour, cayenne pe...
..     ...          ...                                                ...
495   1121      chinese  [ground pepper, garlic, safflower oil, green o...
496  18376      italian  [penne, garlic, eggplant, lemon juice, olive o...
497  17815      italian  [cold water, dry white wine, fish fillets, cho...
498  32878  southern_us  [water, cajun seasoning, yellow onion, shrimp,...
499  24410      british  [mint, large eggs, heavy cream, berries, groun...

[500 rows x 3 columns]

[10259,
 25693,
 20130,
 22213,
 13162,
 6602,
 42779,
 3735,
 16903,
 12734,
 5875,
 45887,
 2698,
 41995,
 31908,
 24717,
 34466,
 1420,
 2941,
 8152,
 13121,
 40523,
 40989,
 29630,
 49136,
 26705,
 27976,
 22087,
 9197,
 1299,
 40429,
 34419,
 10276,
 33465,
 39250,
 37963,
 20051,
 11300,
 17610,
 37405,
 28302,
 31634,
 32304,
 36341,
 29369,
 27564,
 18515,
 3335,
 4499,
 4906,
 5767,
 30748,
 35930,
 44902,
 31119,
 3535,
 47028,
 38112,
 2646,
 5206,
 38233,
 39267,
 11913,
 20591,
 70,
 43928,
 8530,
 275,
 43769,
 49111,
 11886,
 45839,
 699,
 24568,
 8820,
 16582,
 9058,
 4715,
 29061,
 2107,
 22825,
 13758,
 6886,
 14874,
 43399,
 38254,
 41596,
 33989,
 17004,
 4969,
 31831,
 46648,
 36888,
 34471,
 25164,
 39600,
 46357,
 46905,
 8753,
 37337,
 17636,
 8997,
 28851,
 4635,
 7782,
 8031,
 49434,
 31318,
 31027,
 47095,
 4574,
 19757,
 35570,
 44812,
 27858,
 18624,
 9406,
 35132,
 33071,
 8321,
 20955,
 45776,
 6043,
 336,
 25751,
 793,
 34367,
 7406,
 7473,
 7532,
 5924,
 5802,
 41078,
 20665,
 39471,
 9595,
 27869,
 44776,
 17771,
 43970,
 27165,
 11190,
 21872,
 29853,
 1154,
 9069,
 46975,
 4892,
 21467,
 20919,
 42013,
 17821,
 44138,
 5980,
 41961,
 27008,
 31867,
 34248,
 13792,
 38502,
 7023,
 7783,
 2472,
 45193,
 7501,
 34930,
 42967,
 14080,
 45352,
 46205,
 47427,
 40064,
 9010,
 18611,
 35124,
 45605,
 16334,
 32035,
 16810,
 3641,
 43374,
 9112,
 14970,
 41396,
 4748,
 41833,
 18031,
 29734,
 26415,
 29801,
 24351,
 8480,
 27023,
 10425,
 37188,
 24338,
 3457,
 1355,
 40738,
 42380,
 16857,
 2923,
 7528,
 15990,
 27615,
 26061,
 23053,
 5090,
 36862,
 873,
 23726,
 48576,
 25118,
 17586,
 22678,
 428,
 6745,
 31009,
 20983,
 19572,
 15273,
 14198,
 18643,
 17816,
 46893,
 1110,
 21375,
 42833,
 5328,
 17188,
 19622,
 26498,
 27140,
 32353,
 37070,
 2298,
 15291,
 8274,
 23521,
 28342,
 8791,
 242,
 15347,
 20981,
 39391,
 23147,
 44020,
 3245,
 40403,
 33603,
 19691,
 6862,
 20123,
 22712,
 31428,
 9373,
 7666,
 40617,
 26676,
 38067,
 14778,
 636,
 35408,
 22658,
 44866,
 18389,
 40014,
 20863,
 35041,
 30649,
 14351,
 14146,
 48911,
 4252,
 46135,
 20668,
 4009,
 40466,
 32480,
 8223,
 4114,
 3605,
 41363,
 23437,
 9291,
 45423,
 31462,
 45412,
 33048,
 42879,
 6164,
 37704,
 29489,
 6115,
 9829,
 36254,
 23839,
 40283,
 11108,
 42685,
 23629,
 36565,
 42083,
 26032,
 19811,
 30382,
 49175,
 41668,
 9206,
 7322,
 23637,
 43650,
 45593,
 38706,
 38433,
 47826,
 7171,
 18231,
 34385,
 12340,
 33221,
 43228,
 3416,
 23636,
 22822,
 801,
 42007,
 20792,
 44500,
 19004,
 41301,
 16712,
 28250,
 34209,
 1667,
 48571,
 10074,
 43711,
 6440,
 36583,
 10003,
 24738,
 20039,
 29446,
 45711,
 45039,
 46417,
 48080,
 15882,
 49263,
 45956,
 40509,
 11665,
 22997,
 44271,
 29887,
 1764,
 40300,
 45296,
 24365,
 34996,
 47623,
 26464,
 18329,
 43437,
 25375,
 26631,
 26172,
 19747,
 38346,
 31903,
 12099,
 38717,
 30335,
 15171,
 31425,
 36118,
 18190,
 33717,
 15460,
 21052,
 35729,
 45841,
 1182,
 15229,
 31209,
 18271,
 14202,
 10111,
 1128,
 37109,
 9952,
 11164,
 9852,
 45574,
 22581,
 9082,
 30985,
 42612,
 38754,
 45037,
 33197,
 13005,
 18203,
 10210,
 38581,
 32489,
 26647,
 34240,
 8579,
 49639,
 17120,
 27213,
 18621,
 35302,
 27648,
 17658,
 24029,
 45990,
 20692,
 37593,
 46635,
 20149,
 623,
 12048,
 48523,
 16797,
 23336,
 15645,
 39904,
 35962,
 9138,
 47406,
 30250,
 26545,
 13554,
 44562,
 3820,
 49668,
 27688,
 31969,
 33085,
 20061,
 24552,
 27204,
 8304,
 28063,
 38473,
 84,
 12152,
 25201,
 22633,
 41282,
 3040,
 29033,
 40224,
 24640,
 49262,
 28657,
 18842,
 27019,
 2982,
 33222,
 39361,
 13489,
 36461,
 20757,
 35136,
 30327,
 43455,
 36947,
 28056,
 7530,
 47505,
 16520,
 35311,
 22833,
 14398,
 29168,
 22461,
 13615,
 6360,
 40360,
 40182,
 31438,
 31798,
 14342,
 14385,
 14308,
 33841,
 12830,
 23096,
 34026,
 30835,
 15072,
 1121,
 18376,
 17815,
 32878,
 24410]